<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-02AJMVU" ignored="0" name="Test" tests="3" failures="1" timestamp="2020-04-29T14:47:05 CDT" time="16.748" errors="0">
  <testcase name="g" time="0.015" classname="com.regression.Flight_Second_Test">
    <failure type="java.lang.AssertionError" message="This method is failed manually">
      <![CDATA[java.lang.AssertionError: This method is failed manually
at com.regression.Flight_Second_Test.g(Flight_Second_Test.java:14)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- g -->
  <testcase name="f" time="9.729" classname="com.regression.Test_1"/>
  <testcase name="h" time="0.006" classname="com.regression.Flight_Test_Singleton">
    <skipped/>
  </testcase> <!-- h -->
</testsuite> <!-- Test -->
